version: "3.7"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ott
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3308:3306
    networks:
      - springboot-mysql-net
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge